---
title: "README"
author: "Team 5"
date: "2023-02-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Team 5 Course Project

**Checkpoint 1**

Team 5 has established a Git repository for our project and established a cadence of working sessions to collaborate on our individual tasks. So far, we've divided the three pieces of analysis (on the sales data, ACS data, and the merged dataset of the two) among ourselves. We also established our preference to use Tableau for the analysis and visualization. Then, we'll synchronize our efforts into a coherent format that helps understand the data, as well as our team's research question:

-   Are there any preference patterns for liquor consumption among different races? What are most popular liquor categories among geographies with highest share of minorities?

Getting our Git repository set up was a learning experience, as we had not used it extensively before now. I think a huge victory for us was when all three of us were able to pull the cloned repository to our local machines, and can now begin on the work itself.

## 
